version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    versioning-strategy: increase
    commit-message:
      prefix: 'feat(tsgit)'
    allow:
      - dependency-name: '@scolladon/tsgit'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'build'
