version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    versioning-strategy: widen
    commit-message:
      prefix: 'feat(tsgit)'
    cooldown:
      default-days: 0
    allow:
      - dependency-name: '@scolladon/tsgit'
